[[redirects]]
  from = "https://blog.jacobgoodwin.me/*"
  to = "https://blog.jacobgoodwin.me/blog/:splat"
  status = 200

[[redirects]]
  from = "https://jacobgoodwin.me/*"
  to = "https://jacobgoodwin.me/blog/:splat"
  status = 200

[[redirects]]
  from = "https://lessons.jacobgoodwin.me/*"
  to = "https://jacobgoodwin.me/lessons/:splat"
  status = 200