[[redirects]]
from="https://blog.jacobgoodwin.me/*"
to="https://jacobgoodwin.me/blog/:splat"
status=301
force=true
[[redirects]]
from="https://lessons.jacobgoodwin.me/*"
to="https://jacobgoodwin.me/lessons/:splat"
status=301
force=true
[[redirects]]
from="https://professional.jacobgoodwin.me/*"
to="https://jacobgoodwin.me/professional/:splat"
status=301
force=true